### ISSUE TITLE
Add multi-language stream selection

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/plugin.video.showmax#2]
Need a Polish VPS / VPN (that is not blocked) to be able to test.

**Comment by KinoTP** [comment]
Please look also at the problem with subtitles. In Poland every foreign language movie/serie has subtitle which we can on or off, but this add on doesn't see subtitles at all.

**Comment by matthuisman** [comment]
Managed to find a free proxy that using at moment to see a few API calls.

Testing with the movie "The Break-up"
I can't actually play it, but I can get the API data I need.
https://pastebin.com/6Bwzh07q

Found the info I need.
I can see for Polish stuff, multiple video streams are available.

1) Main: Language: Pol  I assume this is dubbed over - @KinoTP can you confirm?
2) Main: Language: Eng (Original audio)
3) Trailer: Language: Eng 

Both have the below subtitles availabe
1) Eng https://api.showmax.com/v97.3/website/catalogue/subtitles/f219fa61-070a-42e2-8243-f5efa6bba50b/8e1251fa-0881-4d37-bb29-2bc9ad5a1e6c
2) Pol https://api.showmax.com/v97.3/website/catalogue/subtitles/f219fa61-070a-42e2-8243-f5efa6bba50b/06bf12b3-1b96-4dad-96e6-cb1ef38e0c2c

I will need to download those subtitle files and convert them to SRT files that KODI supports.
Like this:
https://github.com/Sandmann79/xbmc/blob/40a709f897f1ad575872da44eec360b1aa489081/plugin.video.amazon/resources/lib/play.py#L295

Should be easily done.

How should I select the video stream though?
Select whichever has the language that matches KODI language?
Or show a select dialog when you play?

**Comment by KinoTP** [comment]
Yes, I confirm that pl is the polish language audio.
Maybe could You add an option in add on settings with choice of audio and
subtitle ?

>

**Comment by KinoTP** [comment]
Why inputstream adaptive can't recognize and use subtitles ? We have HBO add
on in Poland and subtitles are working on inputstream add on and there is
no need to download them. Is it possible here ? If not please make what is
easier for You and make subtitle available :)

**Comment by matthuisman** [comment]
It appears Showmax does not embed the subtitles in the video stream.
It's a separate XML:
https://api.showmax.com/v97.3/website/catalogue/subtitles/f219fa61-070a-42e2-8243-f5efa6bba50b/06bf12b3-1b96-4dad-96e6-cb1ef38e0c2c

So, I need to download that and convert it to SRT format, which KODI will recognise.
I'll just do it for all languages as it's pretty quick process and usually only 2x languages.

The amzon add-on etc does the same technique.

**Comment by matthuisman** [comment]
@KinoTP 
Please try this test version of the add-on:
https://drive.google.com/open?id=1WxE0J1hBYsmXdR8AJnx0tJqLgjXscTyr

You should be shown a select language dialog when playing a video.
Also, subtitles should then be available when the video is playing.

I haven't implemented the Default setting yet.

**Comment by KinoTP** [comment]
Now I am at work so I will test It when I'll back home.

śr., 19.09.2018, 09:01 użytkownik Matt Huisman <notifications@github.com>
napisał:

**Comment by matthuisman** [comment]
Closing this as support has been added.
Please leave a comment if there is any issues and I will then re-open
